### ISSUE TITLE
Null SubmodelElement raises an unhandled exception

### ISSUE THREAD

**Issue by martafullen** [eclipse-aaspe/aaspe#37] opened 2024-02-20 15:05 UTC
**Describe the bug**

Aasx files missing a SubmodelElement value raise an unhandled exception during loading.

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=AasxCsharpLibrary
  StackTrace:
   at Extensions.ExtendISubmodelElement.BasicConversionFromV20(ISubmodelElement submodelElement, SubmodelElement sourceSubmodelElement) in \ExtendISubmodelElement.cs:line 504
```

submodelElement is null:

Name | Value | Type
 -- | -- | --
submodelElement | null | AasCore.Aas3_0.ISubmodelElement
sourceSubmodelElement | {"notnull" } | AasxCompatibilityModels.AdminShellV20.SubmodelElement {AasxCompatibilityModels.AdminShellV20.Capability}

**Expected behavior**
Exception caught  
or values checked and nulls handled

**Desktop (please complete the following information):**
 - OS: win 11
 - Version: release AASX Package Explorer V3 2023-11-17.alpha

**Additional context**
Related issue in aasx-server:
https://github.com/eclipse-aaspe/aasx-server/issues/214

**Comment by juileetikekar** [comment] 2024-02-21 15:30
Hi @martafullen,

Thank you for raising the issue!!

The root cause of the issue is unhandled Capability SME during conversion. The fix will be provided asap.

**Comment by juileetikekar** [comment] 2024-02-27 12:47
Hi @martafullen ,

The PR https://github.com/eclipse-aaspe/aaspe/pull/31 fixes this issue. The PR has been merged into the main branch.

**Closed by juileetikekar** 2024-02-27 12:47 UTC
Labels: bug
