### ISSUE TITLE
Unable to open .aasx file which is created by using SAMM CLI

### ISSUE THREAD

**Issue by Punith-Arumilli** [eclipse-aaspe/aaspe#4] opened 2024-01-09 18:09 UTC
Hi,
I created Aspect Model and I converted it into Asset Administration Shell using SAMM CLI. Now if I am trying to open it using AASX Package Explorer it is showing an error.

Loading aasx file repository ..........\Sample_AAS\aasxrepo-new.json ..
File not found when loading aasx file repository ..........\Sample_AAS\aasxrepo-new.json
Application started ..
[AasxPluginAdvancedTextEditor] ListActions() called
[AasxPluginAdvancedTextEditor] InitPlugin() called with args =
[AasxPluginBomStructure] ListActions() called
[AasxPluginBomStructure] InitPlugin() called with args =
[AasxPluginDocumentShelf] InitPlugin() called with args =
[AasxPluginExportTable] ListActions() called
[AasxPluginExportTable] InitPlugin() called with args =
[AasxPluginGenericForms] ListActions() called
[AasxPluginGenericForms] InitPlugin() called with args =
[AasxPluginImageMap] ListActions() called
[AasxPluginImageMap] InitPlugin() called with args =
[AasxPluginMtpViewer] GetPluginName() = MtpViewer
[AasxPluginMtpViewer] ListActions() called
[AasxPluginMtpViewer] InitPlugin() called with args =
[AasxPluginMtpViewer] GetPluginName() = MtpViewer
[AasxPluginPlotting] ListActions() called
[AasxPluginPlotting] InitPlugin() called with args =
[AasxPluginSmdExporter] ListActions() called
[AasxPluginSmdExporter] InitPlugin() called with args =
[AasxPluginTechnicalData] ListActions() called
[AasxPluginTechnicalData] InitPlugin() called with args =
[AasxPluginOpcUaClient] ListActions() called
[AasxPluginUaNetServer] GetPluginName() = Net46AasxServerPlugin
[AasxPluginUaNetServer] ListActions() called
[AasxPluginUaNetServer] InitPlugin() called with args =
[AasxPluginUaNetServer] GetPluginName() = Net46AasxServerPlugin
[AasxPluginWebBrowser] ListActions() called
[AasxPluginWebBrowser] InitPlugin() called with args =
Loading new AASX from: C:\Users\punit\Downloads\MeasurementUnit.aasx as auxiliary False ..
Error: Unhandled exception in AasxPackageExplorer v1.0.0.0: PackageCentral: while performing load from C:\Users\punit\Downloads\MeasurementUnit.aasx at \PackageCentral.cs:line 95 gave: One or more errors occurred. PackageCentral: while performing load from C:\Users\punit\Downloads\MeasurementUnit.aasx at \PackageCentral.cs:line 95 gave: One or more errors occurred.
InnerException: One or more errors occurred.
InnerException: While opening aasx C:\Users\punit\AppData\Local\Temp\tmp905C.aasx from source local file: C:\Users\punit\Downloads\MeasurementUnit.aasx buffered to: C:\Users\punit\AppData\Local\Temp\tmp905C.aasx at \AdminShellPackageEnv.cs:line 402 gave: While reading the AASX C:\Users\punit\AppData\Local\Temp\tmp905C.aasx at \AdminShellPackageEnv.cs:line 313 gave: Part URI must start with a forward slash. at at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 104
at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 294
at AasxPackageExplorer.MainWindow.<CommandBinding_GeneralDispatch>d__5.MoveNext() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.CommandBindings.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler).
Stacktrace: at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 104
at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 294
at AasxPackageExplorer.MainWindow.<CommandBinding_GeneralDispatch>d__5.MoveNext() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.CommandBindings.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Loading new AASX from: C:\Users\punit\Downloads\Universal_Robot.aasx as auxiliary False ..
AASX C:\Users\punit\Downloads\Universal_Robot.aasx loaded.
[AasxPluginExportTable] Export UML data to file: C:\Users\punit\Desktop\new.uml
[AasxPluginExportTable] Export UML data copied to paste buffer.
[AasxPluginExportTable] Export UML data to file: C:\Users\punit\Downloads\new.xml
[AasxPluginExportTable] Export UML data copied to paste buffer.
[AasxPluginExportTable] Exporting table: C:\Users\punit\Downloads\new.docx
Loading new AASX from: C:\Users\punit\Downloads\MeasurementUnit.aasx as auxiliary False ..
Error: Unhandled exception in AasxPackageExplorer v1.0.0.0: PackageCentral: while performing load from C:\Users\punit\Downloads\MeasurementUnit.aasx at \PackageCentral.cs:line 95 gave: One or more errors occurred. PackageCentral: while performing load from C:\Users\punit\Downloads\MeasurementUnit.aasx at \PackageCentral.cs:line 95 gave: One or more errors occurred.
InnerException: One or more errors occurred.
InnerException: While opening aasx C:\Users\punit\AppData\Local\Temp\tmp475F.aasx from source local file: C:\Users\punit\Downloads\MeasurementUnit.aasx buffered to: C:\Users\punit\AppData\Local\Temp\tmp475F.aasx at \AdminShellPackageEnv.cs:line 402 gave: While reading the AASX C:\Users\punit\AppData\Local\Temp\tmp475F.aasx at \AdminShellPackageEnv.cs:line 313 gave: Part URI must start with a forward slash. at at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 104
at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 294
at AasxPackageExplorer.MainWindow.<CommandBinding_GeneralDispatch>d__5.MoveNext() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.CommandBindings.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler).
Stacktrace: at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 104
at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 294
at AasxPackageExplorer.MainWindow.<CommandBinding_GeneralDispatch>d__5.MoveNext() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.CommandBindings.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by BirgitBoss** [comment] 2024-01-27 22:09
This issue is addressed by https://github.com/admin-shell-io/aasx-package-explorer/issues/666 and https://github.com/eclipse-aas4j/aas4j/issues/158
This issue is redundant and can be closed.

**Comment by juileetikekar** [comment] 2024-02-12 11:39
The issue is related to https://github.com/admin-shell-io/aasx-package-explorer/issues/654#issuecomment-1849477557 and has been fixed.

**Closed by juileetikekar** 2024-02-12 11:39 UTC
